// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phufwxorapcypsjfhrni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodWZ3eG9yYXBjeXBzamZocm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzEwODQsImV4cCI6MjA2NzcwNzA4NH0.VIaovUpMmea5P1rKLMS8AZkkMVvpgTghp5hExJYdLuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});