// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nelioyzsdyxufjlorzcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lbGlveXpzZHl4dWZqbG9yemNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Mzg3NzgsImV4cCI6MjA3MDUxNDc3OH0.8TF_AdMHW3vH7PGFFhUqevsHe07u0bJ_4uNAGcW1ehU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});