name: Android CI - Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx1g"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Make gradlew executable if present
        run: |
          if [ -f "./gradlew" ]; then
            echo "Found gradlew -> making executable"
            chmod +x ./gradlew
          else
            echo "No gradlew in repo root; will install system gradle if needed."
          fi
        shell: bash

      - name: Decode keystore (optional)
        run: |
          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "Decoding keystore..."
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
          else
            echo "No KEYSTORE_BASE64 secret provided; skipping keystore decode."
          fi
        shell: bash

      - name: Build APK (debug)
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug
          else
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle assembleDebug
          fi
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      - name: Build APK (release)
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleRelease
          else
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle assembleRelease
          fi
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            app/build/outputs/**/*.apk
